FROM ghcr.io/jonsson-analytics/devcontainer-base:main

COPY --chown=vscode --from=sccache /home/vscode/.cargo/bin/sccache .cargo/bin/sccache
COPY --chown=vscode --from=cargo-watch /home/vscode/.cargo/bin/cargo-watch .cargo/bin/cargo-watch
COPY --chown=vscode --from=nu /home/vscode/.cargo/bin/nu .cargo/bin/nu
COPY --chown=vscode --from=coreutils /home/vscode/.cargo/bin/coreutils .cargo/bin/coreutils
COPY --chown=vscode --from=starship /home/vscode/.cargo/bin/starship .cargo/bin/starship
COPY --chown=vscode --from=exa /home/vscode/.cargo/bin/exa .cargo/bin/exa
COPY --chown=vscode --from=bat /home/vscode/.cargo/bin/bat .cargo/bin/bat
COPY --chown=vscode --from=ripgrep /home/vscode/.cargo/bin/rg .cargo/bin/rg
COPY --chown=vscode --from=fd-find /home/vscode/.cargo/bin/fd .cargo/bin/fd
COPY --chown=vscode --from=du-dust /home/vscode/.cargo/bin/dust .cargo/bin/dust
COPY --chown=vscode --from=zellij /home/vscode/.cargo/bin/zellij .cargo/bin/zellij
COPY --chown=vscode --from=mprocs /home/vscode/.cargo/bin/mprocs .cargo/bin/mprocs
COPY --chown=vscode --from=gitui /home/vscode/.cargo/bin/gitui .cargo/bin/gitui
COPY --chown=vscode --from=bacon /home/vscode/.cargo/bin/bacon .cargo/bin/bacon
COPY --chown=vscode --from=cargo-info /home/vscode/.cargo/bin/cargo-info .cargo/bin/cargo-info
COPY --chown=vscode --from=speedtest-rs /home/vscode/.cargo/bin/speedtest-rs .cargo/bin/speedtest-rs
COPY --chown=vscode --from=rtx-cli /home/vscode/.cargo/bin/rtx .cargo/bin/rtx
COPY --chown=vscode --from=bottom /home/vscode/.cargo/bin/btm .cargo/bin/btm
COPY --chown=vscode --from=procs /home/vscode/.cargo/bin/procs .cargo/bin/procs
COPY --chown=vscode --from=sd /home/vscode/.cargo/bin/sd .cargo/bin/sd
COPY --chown=vscode --from=tokei /home/vscode/.cargo/bin/tokei .cargo/bin/tokei
COPY --chown=vscode --from=hyperfine /home/vscode/.cargo/bin/hyperfine .cargo/bin/hyperfine
COPY --chown=vscode --from=bandwhich /home/vscode/.cargo/bin/bandwhich .cargo/bin/bandwhich
COPY --chown=vscode --from=delta /home/vscode/.cargo/bin/delta .cargo/bin/delta
COPY --chown=vscode --from=zoxide /home/vscode/.cargo/bin/zoxide .cargo/bin/zoxide
COPY --chown=vscode --from=broot /home/vscode/.cargo/bin/broot .cargo/bin/broot
