on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths:
      - .github/workflows/build-image.yml
      - src/**

env:
  registry: ghcr.io
  profile: default
  toolchain: nightly-2023-03-13

jobs:
  base:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: |
            ${{ env.registry }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          file: src/base.Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            TOOLCHAIN=${{ env.toolchain }}
            PROFILE=${{ env.profile }}
  
  app-bacon:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: bacon

  app-bandwhich:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: bandwhich

  app-bat:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: bat

  app-bottom:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: bottom

  app-broot:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: broot

  app-cargo-info:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: cargo-info

  app-cargo-watch:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: cargo-watch

  app-coreutils:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: coreutils
  
  app-delta:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: delta

  app-du-dust:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: du-dust

  app-exa:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: exa

  app-fd-find:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: fd-find

  app-gitui:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: gitui

  app-hyperfine:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: hyperfine

  app-mprocs:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: mprocs

  app-nu:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: nu

  app-procs:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: procs

  app-ripgrep:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: ripgrep

  app-rtx-cli:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: rtx-cli

  app-sccache:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: sccache

  app-sd:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: sd

  app-speedtest-rs:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: speedtest-rs

  app-starship:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: starship

  app-tokei:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: tokei

  app-zellij:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: zellij

  app-zoxide:
    needs: base
    uses: jonsson-analytics/devcontainer-base/.github/workflows/build-app.yml@main
    with:
      app: zoxide

  profile-full:
    needs:
      - app-bacon
      - app-bandwhich
      - app-bat
      - app-bottom
      - app-broot
      - app-cargo-info
      - app-cargo-watch
      - app-coreutils
      - app-delta
      - app-du-dust
      - app-exa
      - app-fd-find
      - app-gitui
      - app-hyperfine
      - app-mprocs
      - app-nu
      - app-procs
      - app-ripgrep
      - app-rtx-cli
      - app-sccache
      - app-sd
      - app-speedtest-rs
      - app-starship
      - app-tokei
      - app-zellij
      - app-zoxide

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: |
            ${{ env.registry }}/${{ github.repository }}/profiles/full
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          file: src/profiles/full.Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            TOOLCHAIN=${{ env.toolchain }}
            PROFILE=${{ env.profile }}
